import 'reflect-metadata'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import { NestFactory } from '@nestjs/core'
import request from 'supertest'
import type { INestApplication } from '@nestjs/common'
import { AppModule } from './app.module.js'
import { ApiErrorFilter } from './common/error.filter.js'

const binary=(res:NodeJS.ReadableStream,done:(error:Error|null,body?:Buffer)=>void)=>{const chunks:Buffer[]=[];res.on('data',(chunk:Buffer)=>chunks.push(chunk));res.on('end',()=>done(null,Buffer.concat(chunks)));res.on('error',(error:Error)=>done(error))}

describe('authenticated project flow',()=>{
  let app:INestApplication,cookie='',csrf='',workspaceId='',projectId='',columnId='',columnId2='',taskId='',currentUserId='',version=0
  beforeAll(async()=>{app=await NestFactory.create(AppModule,{logger:false});app.setGlobalPrefix('api/v1',{exclude:['mcp']});app.useGlobalFilters(new ApiErrorFilter());await app.init()})
  afterAll(async()=>app.close())
  it('registers and logs in',async()=>{const email=`test-${Date.now()}@example.com`,password='secure-password',registration={email,password,name:'测试用户',workspaceName:'测试空间'};await request(app.getHttpServer()).post('/api/v1/auth/register').send(registration).expect(201);const duplicate=await request(app.getHttpServer()).post('/api/v1/auth/register').send(registration).expect(409);expect(duplicate.body.code).toBe('EMAIL_EXISTS');const previousNodeEnv=process.env.NODE_ENV,previousOrigin=process.env.APP_ORIGIN;process.env.NODE_ENV='production';process.env.APP_ORIGIN='http://example.com';const response=await request(app.getHttpServer()).post('/api/v1/auth/login').send({email,password}).expect(201);if(previousNodeEnv===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=previousNodeEnv;if(previousOrigin===undefined)delete process.env.APP_ORIGIN;else process.env.APP_ORIGIN=previousOrigin;expect(response.headers['set-cookie'][0]).not.toContain('Secure');cookie=response.headers['set-cookie'][0].split(';')[0];csrf=response.body.csrfToken;currentUserId=response.body.user.id;expect(cookie).toContain('session=')})
  it('isolates workspace resources and creates a task',async()=>{const workspaces=await request(app.getHttpServer()).get('/api/v1/workspaces').set('Cookie',cookie).expect(200);workspaceId=workspaces.body[0].id;const projects=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects`).set('Cookie',cookie).expect(200);projectId=projects.body[0].id;const columns=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects/${projectId}/columns`).set('Cookie',cookie).expect(200);columnId=columns.body[0].id;columnId2=columns.body[1].id;const task=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/tasks`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,columnId,title:'集成测试任务'}).expect(201);taskId=task.body.id;version=task.body.version;expect(task.body.key).toBe('TEAM-1');const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(1)})
  it('persists task details and rejects stale concurrent updates',async()=>{await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/${taskId}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'第一次更新',description:'验收描述',labels:['回归'],dueDate:'2026-07-20',version}).expect(200);const listed=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(listed.body.data[0]).toMatchObject({description:'验收描述',labels:['回归'],dueDate:'2026-07-20'});const conflict=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/${taskId}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'过期更新',version}).expect(409);expect(conflict.body.code).toBe('TASK_VERSION_CONFLICT')})
  it('updates and deletes selected tasks in bulk',async()=>{const first=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/tasks`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,columnId,title:'批量任务一'}).expect(201),second=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/tasks`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,columnId,title:'批量任务二'}).expect(201),taskIds=[first.body.id,second.body.id];await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/bulk`).set('Cookie',cookie).set('x-csrf-token',csrf).send({taskIds,action:{type:'ASSIGN',assigneeIds:[currentUserId]}}).expect(200);await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/bulk`).set('Cookie',cookie).set('x-csrf-token',csrf).send({taskIds,action:{type:'PRIORITY',priority:'HIGH'}}).expect(200);await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/bulk`).set('Cookie',cookie).set('x-csrf-token',csrf).send({taskIds,action:{type:'MOVE',columnId:columnId2}}).expect(200);const listed=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200),changed=listed.body.data.filter((task:{id:string})=>taskIds.includes(task.id));expect(changed).toHaveLength(2);expect(changed.every((task:{priority:string;columnId:string;assignees:{id:string}[]})=>task.priority==='HIGH'&&task.columnId===columnId2&&task.assignees[0]?.id===currentUserId)).toBe(true);await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/bulk`).set('Cookie',cookie).set('x-csrf-token',csrf).send({taskIds,action:{type:'DELETE'}}).expect(200);const remaining=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(remaining.body.data).toHaveLength(1)})
  it('versions design documents and rejects stale saves',async()=>{const created=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/documents`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'接口设计',projectId,content:'# v1'}).expect(201);const updated=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({content:'# v2',version:1,changeNote:'补充接口'}).expect(200);expect(updated.body.version).toBe(2);const versions=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}/versions`).set('Cookie',cookie).expect(200);expect(versions.body.map((item:{version:number})=>item.version)).toEqual([2,1]);const conflict=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({content:'# stale',version:1}).expect(409);expect(conflict.body.code).toBe('DOCUMENT_VERSION_CONFLICT')})
  it('applies a reviewed plan exactly once',async()=>{const plan=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,title:'发布计划',goal:'准备发布',items:[{title:'补齐回归测试',kind:'TASK'},{title:'修复登录缺陷',kind:'BUG',priority:'HIGH'}]}).expect(201);const first=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans/${plan.body.id}/apply`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);const second=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans/${plan.body.id}/apply`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);expect(first.body.taskIds).toHaveLength(2);expect(second.body).toMatchObject({alreadyApplied:true,taskIds:first.body.taskIds});const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(3)})
  it('issues a one-time MCP token and accepts Streamable HTTP initialization',async()=>{const created=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/mcp-tokens`).set('Cookie',cookie).set('x-csrf-token',csrf).send({name:'集成测试',write:true}).expect(201);expect(created.body.token).toMatch(/^thm_/);const listed=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/mcp-tokens`).set('Cookie',cookie).expect(200);expect(listed.body[0].token).toBeUndefined();const initialized=await request(app.getHttpServer()).post('/mcp').set('Authorization',`Bearer ${created.body.token}`).set('Accept','application/json, text/event-stream').send({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'integration-test',version:'1.0.0'}}}).expect(200);expect(initialized.body.result.serverInfo.name).toBe('task-harbor')})
  it('exports, previews, and restores a portable workspace archive',async()=>{const exported=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/export`).set('Cookie',cookie).buffer(true).parse(binary).expect(200);expect(Buffer.isBuffer(exported.body)).toBe(true);const preview=await request(app.getHttpServer()).post('/api/v1/workspaces/import/preview').set('Cookie',cookie).set('x-csrf-token',csrf).attach('file',exported.body,'workspace.taskharbor.zip').expect(201);expect(preview.body.counts).toMatchObject({projects:1,tasks:3,documents:1,plans:1});const restored=await request(app.getHttpServer()).post('/api/v1/workspaces/import').set('Cookie',cookie).set('x-csrf-token',csrf).attach('file',exported.body,'workspace.taskharbor.zip');expect(restored.status,JSON.stringify(restored.body)).toBe(201);const importedProjects=await request(app.getHttpServer()).get(`/api/v1/workspaces/${restored.body.id}/projects`).set('Cookie',cookie).expect(200);expect(importedProjects.body).toHaveLength(1);const importedTasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${restored.body.id}/tasks?projectId=${importedProjects.body[0].id}`).set('Cookie',cookie).expect(200);expect(importedTasks.body.data).toHaveLength(3)})
  it('rejects a restore request without a backup file',async()=>{const response=await request(app.getHttpServer()).post('/api/v1/workspaces/import/preview').set('Cookie',cookie).set('x-csrf-token',csrf).expect(400);expect(response.body.code).toBe('BACKUP_FILE_REQUIRED')})
  it('mirrors to GitHub and queues pull conflicts without overwriting local tasks',async()=>{let issueNumber=0;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input),method=init?.method??'GET';if(url.endsWith('/repos/baicie/task-harbor')&&method==='GET')return new Response(JSON.stringify({full_name:'baicie/task-harbor'}),{status:200});if(url.includes('/issues?'))return new Response(JSON.stringify([{number:1,title:'远程修改标题',body:'远程描述',state:'open',labels:[]},{number:99,title:'GitHub 新任务',body:'从 GitHub 导入',state:'open',labels:['bug']}]),{status:200});if(url.includes('/issues')&&(method==='POST'||method==='PATCH'))return new Response(JSON.stringify({number:method==='POST'?++issueNumber:Number(url.split('/').pop()),title:'ok',body:'',state:'open',labels:[]}),{status:200});if(url.includes('/contents/')&&method==='PUT')return new Response(JSON.stringify({content:{sha:'abc123'}}),{status:200});return new Response('{}',{status:404})});try{await request(app.getHttpServer()).put(`/api/v1/workspaces/${workspaceId}/integrations/github`).set('Cookie',cookie).set('x-csrf-token',csrf).send({repoUrl:'https://github.com/baicie/task-harbor',token:'github_pat_integration_test_token',projectId}).expect(200);const pushed=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/integrations/github/push`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);expect(pushed.body).toEqual({tasks:3,documents:1});const pulled=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/integrations/github/pull`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);expect(pulled.body).toEqual({imported:1,conflicts:1});const conflicts=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/integrations/github/conflicts`).set('Cookie',cookie).expect(200);expect(conflicts.body).toHaveLength(1);await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/integrations/github/conflicts/${conflicts.body[0].id}/resolve`).set('Cookie',cookie).set('x-csrf-token',csrf).send({resolution:'KEEP_LOCAL'}).expect(201)}finally{fetchMock.mockRestore()}})
  it('soft deletes a project and its tasks',async()=>{await request(app.getHttpServer()).delete(`/api/v1/workspaces/${workspaceId}/projects/${projectId}`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(200);const projects=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects`).set('Cookie',cookie).expect(200);expect(projects.body).toHaveLength(0);const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(0)})
})
