import 'reflect-metadata'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { NestFactory } from '@nestjs/core'
import request from 'supertest'
import type { INestApplication } from '@nestjs/common'
import { AppModule } from './app.module.js'
import { ApiErrorFilter } from './common/error.filter.js'

describe('authenticated project flow',()=>{
  let app:INestApplication,cookie='',csrf='',workspaceId='',projectId='',columnId='',taskId='',version=0
  beforeAll(async()=>{app=await NestFactory.create(AppModule,{logger:false});app.setGlobalPrefix('api/v1');app.useGlobalFilters(new ApiErrorFilter());await app.init()})
  afterAll(async()=>app.close())
  it('registers and logs in',async()=>{const email=`test-${Date.now()}@example.com`,password='secure-password';await request(app.getHttpServer()).post('/api/v1/auth/register').send({email,password,name:'测试用户',workspaceName:'测试空间'}).expect(201);const response=await request(app.getHttpServer()).post('/api/v1/auth/login').send({email,password}).expect(201);cookie=response.headers['set-cookie'][0].split(';')[0];csrf=response.body.csrfToken;expect(cookie).toContain('session=')})
  it('isolates workspace resources and creates a task',async()=>{const workspaces=await request(app.getHttpServer()).get('/api/v1/workspaces').set('Cookie',cookie).expect(200);workspaceId=workspaces.body[0].id;const projects=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects`).set('Cookie',cookie).expect(200);projectId=projects.body[0].id;const columns=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects/${projectId}/columns`).set('Cookie',cookie).expect(200);columnId=columns.body[0].id;const task=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/tasks`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,columnId,title:'集成测试任务'}).expect(201);taskId=task.body.id;version=task.body.version;expect(task.body.key).toBe('TEAM-1');const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(1)})
  it('rejects stale concurrent updates',async()=>{await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/${taskId}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'第一次更新',version}).expect(200);const conflict=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/tasks/${taskId}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'过期更新',version}).expect(409);expect(conflict.body.code).toBe('TASK_VERSION_CONFLICT')})
  it('versions design documents and rejects stale saves',async()=>{const created=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/documents`).set('Cookie',cookie).set('x-csrf-token',csrf).send({title:'接口设计',projectId,content:'# v1'}).expect(201);const updated=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({content:'# v2',version:1,changeNote:'补充接口'}).expect(200);expect(updated.body.version).toBe(2);const versions=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}/versions`).set('Cookie',cookie).expect(200);expect(versions.body.map((item:{version:number})=>item.version)).toEqual([2,1]);const conflict=await request(app.getHttpServer()).patch(`/api/v1/workspaces/${workspaceId}/documents/${created.body.id}`).set('Cookie',cookie).set('x-csrf-token',csrf).send({content:'# stale',version:1}).expect(409);expect(conflict.body.code).toBe('DOCUMENT_VERSION_CONFLICT')})
  it('applies a reviewed plan exactly once',async()=>{const plan=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans`).set('Cookie',cookie).set('x-csrf-token',csrf).send({projectId,title:'发布计划',goal:'准备发布',items:[{title:'补齐回归测试',kind:'TASK'},{title:'修复登录缺陷',kind:'BUG',priority:'HIGH'}]}).expect(201);const first=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans/${plan.body.id}/apply`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);const second=await request(app.getHttpServer()).post(`/api/v1/workspaces/${workspaceId}/plans/${plan.body.id}/apply`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(201);expect(first.body.taskIds).toHaveLength(2);expect(second.body).toMatchObject({alreadyApplied:true,taskIds:first.body.taskIds});const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(3)})
  it('soft deletes a project and its tasks',async()=>{await request(app.getHttpServer()).delete(`/api/v1/workspaces/${workspaceId}/projects/${projectId}`).set('Cookie',cookie).set('x-csrf-token',csrf).expect(200);const projects=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/projects`).set('Cookie',cookie).expect(200);expect(projects.body).toHaveLength(0);const tasks=await request(app.getHttpServer()).get(`/api/v1/workspaces/${workspaceId}/tasks?projectId=${projectId}`).set('Cookie',cookie).expect(200);expect(tasks.body.data).toHaveLength(0)})
})
