import { FormEvent, useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, ListChecks, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { api, type Subtask } from '@/api'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'

export default function TaskSubtasks({workspaceId,taskId,en,onChanged}:{workspaceId:string;taskId:string;en:boolean;onChanged:()=>Promise<void>}){
  const [items,setItems]=useState<Subtask[]>([]),[title,setTitle]=useState(''),[busy,setBusy]=useState(false)
  const load=()=>api.subtasks(workspaceId,taskId).then(setItems).catch(reason=>toast.error(reason instanceof Error?reason.message:(en?'Failed to load subtasks':'子任务加载失败')))
  useEffect(()=>{void load()},[workspaceId,taskId])
  const add=async(event:FormEvent)=>{event.preventDefault();const next=title.trim();if(!next)return;setBusy(true);try{const created=await api.createSubtask(workspaceId,taskId,next);setItems(current=>[...current,created]);setTitle('');await onChanged()}catch(reason){toast.error(reason instanceof Error?reason.message:(en?'Failed to add subtask':'添加子任务失败'))}finally{setBusy(false)}}
  const toggle=async(item:Subtask)=>{const isDone=!item.isDone;setItems(current=>current.map(value=>value.id===item.id?{...value,isDone}:value));try{await api.updateSubtask(workspaceId,taskId,item.id,{isDone});await onChanged()}catch(reason){setItems(current=>current.map(value=>value.id===item.id?item:value));toast.error(reason instanceof Error?reason.message:(en?'Update failed':'更新失败'))}}
  const remove=async(item:Subtask)=>{setBusy(true);try{await api.deleteSubtask(workspaceId,taskId,item.id);setItems(current=>current.filter(value=>value.id!==item.id));await onChanged()}catch(reason){toast.error(reason instanceof Error?reason.message:(en?'Delete failed':'删除失败'))}finally{setBusy(false)}}
  const move=async(index:number,offset:-1|1)=>{const target=index+offset;if(target<0||target>=items.length)return;const previous=items,next=[...items];[next[index],next[target]]=[next[target]!,next[index]!];setItems(next);setBusy(true);try{await api.reorderSubtasks(workspaceId,taskId,next.map(item=>item.id));await onChanged()}catch(reason){setItems(previous);toast.error(reason instanceof Error?reason.message:(en?'Reorder failed':'排序失败'))}finally{setBusy(false)}}
  const done=items.filter(item=>item.isDone).length,percent=items.length?done/items.length*100:0
  return <section className="task-subtasks"><div className="task-subtasks-heading"><span><ListChecks/><strong>{en?'Subtasks':'子任务'}</strong></span><small>{done}/{items.length}</small></div>{items.length?<><div className="subtask-progress" aria-label={en?`${done} of ${items.length} subtasks complete`:`已完成 ${done}/${items.length} 个子任务`}><i style={{width:`${percent}%`}}/></div><div className="subtask-list">{items.map((item,index)=><div key={item.id}><Checkbox aria-label={item.title} checked={item.isDone} onCheckedChange={()=>void toggle(item)}/><span data-done={item.isDone||undefined}>{item.title}</span><span className="subtask-actions"><Button type="button" size="icon-sm" variant="ghost" disabled={busy||index===0} aria-label={en?'Move subtask up':'上移子任务'} onClick={()=>void move(index,-1)}><ArrowUp/></Button><Button type="button" size="icon-sm" variant="ghost" disabled={busy||index===items.length-1} aria-label={en?'Move subtask down':'下移子任务'} onClick={()=>void move(index,1)}><ArrowDown/></Button><Button type="button" size="icon-sm" variant="ghost" disabled={busy} aria-label={en?'Delete subtask':'删除子任务'} onClick={()=>void remove(item)}><Trash2/></Button></span></div>)}</div></>:null}<form className="subtask-composer" onSubmit={add}><Input value={title} maxLength={300} disabled={busy} placeholder={en?'Add a subtask':'添加一个子任务'} onChange={event=>setTitle(event.target.value)}/><Button type="submit" size="icon" disabled={busy||!title.trim()} aria-label={en?'Add subtask':'添加子任务'}><Plus/></Button></form></section>
}
